
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/hw6db
    username: hw6
    password: hw6
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
      show-sql: true
  application:
    name: Microservice1
server:
  port: 8081



